baseurl = "http://donsoft.io/blog"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-GB"
layoutdir = "layouts"
publishdir = "public"
author = "Donald Whyte"
title = "Don's Thoughts"
disqusshortname = "donsoft-blog"
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 02, 2006"
dateformfull = "Mon Jan 2 2006 UTC"
description = "TODO"
copyright = "Copyright © 2017 Donald Whyte"
logofile = "img/logo.jpg"
faviconfile = "img/favicon.png"
highlightjs = true
progressively = true
latestpostcount = 3
github = "DonaldWhyte"
email = "don@donsoft.io"
linkedin = "donaldwhyte"
twitter = "donald_whyte"
social_banner = "img/banner.png"
